from dotenv import load_dotenv
import os

load_dotenv()
EMAIL_USUARIO = os.getenv("EMAIL_USUARIO")
SENHA_APP = os.getenv("SENHA_APP")
GOOGLE_CREDENTIALS_PATH = os.getenv("GOOGLE_CREDENTIALS")
TELEGRAM_BOT_TOKEN = "7694246823:AAFJdd7IjQ5X8-WCYOzW0-HYWYKlPJh1h_U"
TELEGRAM_CHAT_ID = "7175895401"
